spring:
   datasource:
      url: jdbc:mysql://localhost:3306/learning_portal?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialization-mode: always
   jpa:
      hibernate.ddl-auto: update

server:
   servlet:
      contextPath: /api/v1/


price:
  countryTax:
     91:
        Tax: "10%"
        CurrencySymbol: "INR"
     01:
        Tax: "15%"
        ConversionFee: "100"
        CurrencySymbol: "$"
     